// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK302-h3aOMZuK-8Gpbpj8yN3CkDyB-30',
    appId: '1:473717940748:web:542f9cad4406ffc4fac429',
    messagingSenderId: '473717940748',
    projectId: 'monitorapps-arfobhekel2',
    authDomain: 'monitorapps-arfobhekel2.firebaseapp.com',
    databaseURL: 'https://monitorapps-arfobhekel2-default-rtdb.firebaseio.com',
    storageBucket: 'monitorapps-arfobhekel2.firebasestorage.app',
    measurementId: 'G-FZ2M1QMTX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-i5H5Zq-au1QtwLJastgrvgR21RwvWTk',
    appId: '1:473717940748:android:86cae3c42118f0e0fac429',
    messagingSenderId: '473717940748',
    projectId: 'monitorapps-arfobhekel2',
    databaseURL: 'https://monitorapps-arfobhekel2-default-rtdb.firebaseio.com',
    storageBucket: 'monitorapps-arfobhekel2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC15T66NMbB94JO1nq16qRpsohzoFO1Vos',
    appId: '1:473717940748:ios:7d9069f13f6e6327fac429',
    messagingSenderId: '473717940748',
    projectId: 'monitorapps-arfobhekel2',
    databaseURL: 'https://monitorapps-arfobhekel2-default-rtdb.firebaseio.com',
    storageBucket: 'monitorapps-arfobhekel2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC15T66NMbB94JO1nq16qRpsohzoFO1Vos',
    appId: '1:473717940748:ios:7d9069f13f6e6327fac429',
    messagingSenderId: '473717940748',
    projectId: 'monitorapps-arfobhekel2',
    databaseURL: 'https://monitorapps-arfobhekel2-default-rtdb.firebaseio.com',
    storageBucket: 'monitorapps-arfobhekel2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK302-h3aOMZuK-8Gpbpj8yN3CkDyB-30',
    appId: '1:473717940748:web:cee432a8025fe021fac429',
    messagingSenderId: '473717940748',
    projectId: 'monitorapps-arfobhekel2',
    authDomain: 'monitorapps-arfobhekel2.firebaseapp.com',
    databaseURL: 'https://monitorapps-arfobhekel2-default-rtdb.firebaseio.com',
    storageBucket: 'monitorapps-arfobhekel2.firebasestorage.app',
    measurementId: 'G-803QXZJPL6',
  );

}